### ISSUE TITLE
Logged Out Cart 

### ISSUE THREAD

**Issue by jponto** [Fullstack-2101-ft-Pits-Protectors/graceshopper-project#20]
**Feature**
- As a logged out user, I want to be able to add items to cart, edit, and delete them
- I want to be able to start checkout process as a logged out user
- p0: When I log in, I want my user db cart to be my new cart
- When I log out, I want the items in my cart to persist
- p2: When I log in, I want my existing cart to merge with any preexisting cart related to my user

**Tasks**
- [x] Create local store
- [x] Add get, edit, delete, and add routes to access local store
- [x] Enable access to local cart on any page
- [x] Investigate merging local cart with user db cart on login without doubling preexisting item quantity
